#!/bin/bash
#
# Update a fresh install of Ubuntu Server 16.04 to a base
# image suitable for further configuration.

set -e

export DEBIAN_FRONTEND=noninteractive

GMAIL_SMTP_PASS_PATH=/etc/agolden/GMAIL_SMTP_PASS
GMAIL_SMTP_USER_PATH=/etc/agolden/GMAIL_SMTP_USER
UNATTENDED_UPGRADES_CONF_PATH=/etc/apt/apt.conf.d/50unattended-upgrades
MAIL_AUTH_DIR=/etc/mail/authinfo/
LOCAL_USER=alex
LOCAL_USER_SSH_PATH=/home/$LOCAL_USER/.ssh
NO_MAIL="false"

while getopts 'm' flag; do
  case "${flag}" in
    m) NO_MAIL="true" ;;
    *) error "Unexpected option ${flag}" ;;
  esac
done

# Set FQDN
cat hosts > /etc/hosts

sed -i '/deb cdrom/d' /etc/apt/sources.list

sudo apt-get update && \
  apt-get upgrade -yq && \
  apt-get dist-upgrade -yq && \
  apt-get install -yq wget \
    unattended-upgrades \
    sendmail \
    mailutils \
    sendmail-bin \
    ssh \
    wget

# Configure email for root

if ["$NO_MAIL" == "false"]; then

  # Read in the relevant secrets
  chmod 400 $GMAIL_SMTP_PASS_PATH
  GMAIL_SMTP_PASS=$(<$GMAIL_SMTP_PASS_PATH)

  chmod 400 $GMAIL_SMTP_USER_PATH
  GMAIL_SMTP_USER=$(<$GMAIL_SMTP_USER_PATH)

  mkdir -p -m 700 $MAIL_AUTH_DIR

  sed -e "s/\${GMAIL_SMTP_USER}/$GMAIL_SMTP_USER/" gmail-auth > $MAIL_AUTH_DIR'gmail-auth'
  sed -i "s/\${GMAIL_SMTP_PASS}/$GMAIL_SMTP_PASS/" $MAIL_AUTH_DIR'gmail-auth'
  chmod 400 $MAIL_AUTH_DIR'gmail-auth'

  cat sendmail.mc > /etc/mail/sendmail.mc
  pushd $MAIL_AUTH_DIR
  makemap hash gmail-auth < gmail-auth
  cd ..
  make -C /etc/mail
  /etc/init.d/sendmail reload
  popd
fi

# Install root and intermediate certificates
pushd /usr/local/share/ca-certificates
wget -O ca.crt "https://drive.google.com/a/agolden.com/uc?export=download&id=0B-2mJXSMz6FLSEZLQmVMUmxoVDQ"
wget -O intermediate.crt "https://drive.google.com/a/agolden.com/uc?export=download&id=0B-2mJXSMz6FLRkZLaHMtZTBvTDQ"
update-ca-certificates
popd

# Enable certificate-based SSH
mkdir -p -m 700 ~/.ssh
cat authorized_keys > $LOCAL_USER_SSH_PATH'/authorized_keys'
chmod 600 $LOCAL_USER_SSH_PATH'/authorized_keys'
chown -R $LOCAL_USER:$LOCAL_USER $LOCAL_USER_SSH_PATH
cat sshd_config > /etc/ssh/sshd_config
service sshd restart
